from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import time

def open_eway_portal(ewb_no, invoice_no, date, gstin="24AHJPR6707K1ZY"):
    """
    Opens the e-way bill download page, fills all known fields,
    and waits for user to complete the captcha manually.
    """
    try:
        # --- Chrome Options ---
        options = Options()
        options.add_argument("--start-maximized")
        # options.add_argument("--headless")  # uncomment if you want hidden

        # --- Start driver ---
        driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
        driver.get("https://ewaybillgst.gov.in/Others/EBPrintnew.aspx")

        wait = WebDriverWait(driver)

        # --- Fill E-Way Bill Number ---
        ewb_field = wait.until(EC.presence_of_element_located((By.ID, "ctl00_ContentPlaceHolder1_txt_ebillno")))
        ewb_field.clear()
        ewb_field.send_keys(ewb_no)

        # --- Fill Date ---
        date_field = driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_txt_date")
        date_field.clear()
        date_field.send_keys(date)

        # --- Fill Generated By (Supplier GSTIN) ---
        genby_field = driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_txt_genby")
        genby_field.clear()
        genby_field.send_keys(gstin)

        # --- Fill Document Number ---
        doc_field = driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_txt_doc_no")
        doc_field.clear()
        doc_field.send_keys(invoice_no)

        print("\n✅ All fields filled automatically.")
        print("👉 Please enter the captcha manually and click 'Go' on the website.")
        print("Keep this window open until download completes.\n")

        # --- Keep browser open until user closes manually ---
        while True:
            time.sleep(2)

    except Exception as e:
        print(f"❌ Error: {e}")
